"""add skill_level to users

Revision ID: 4da3fb106d9f
Revises: d6446c5ba1cd
Create Date: 2026-06-23 09:35:06.768942

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4da3fb106d9f'
down_revision = 'd6446c5ba1cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.alter_column('concept_tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.alter_column('concept_tags',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR(length=50)),
               existing_nullable=True)

    # ### end Alembic commands ###
