"""Add ai_interactions table

Revision ID: d6446c5ba1cd
Revises: 41e3b869f781
Create Date: 2026-06-10 18:51:43.808316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6446c5ba1cd'
down_revision = '41e3b869f781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_interactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_interactions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_interactions_user_id'))

    op.drop_table('ai_interactions')
    # ### end Alembic commands ###
